Repository shivshankar9/Student-portal, pull requests merged in 2022-01, with the labels that each got.

#124 Text to pdf functionality added
  Text-to-pdf.html
  index.html
  js/main.js
  textToPdf.css
Labels: SWOC, EASY

#129 Added Image to PDF
  Img-to-Pdf/ConvertImg2Pdf.py
  Img-to-Pdf/generatedPdf.pdf
  Img-to-Pdf/index.css
  Img-to-Pdf/index.html
  Img-to-Pdf/index.js
  Img-to-Pdf/main.js
  Img-to-Pdf/requirements.txt
  Img-to-Pdf/script.js
  Img-to-Pdf/style.css
  index.html
Labels: SWOC

#132 Corrected logos in functionality page.
  Word-to-Pdf/index.html
  Word-to-Pdf/main.js
Labels: SWOC, BEGINNER, EASY

#138 Added image resizer functionality
  css/homepage.css
  imageresize.css
  imageresize.html
  imageresize.js
  images/Imgresize.png
  index.html
Labels: SWOC, MEDIUM

#154 foldername changed to fix the error in text to pdf feature
  Text-to-pdf/index.html
  Text-to-pdf/main.js
  Text-to-pdf/script.js
  Text-to-pdf/style.css
Labels: SWOC, BEGINNER
